config/routes.rb
AccordianNotes::Application.routes.draw do
  resources :users

  resources :apatients

  resources :pnotes

  get "smartmenus/show"
  get "menumaster/show"
  get "multiplemaster/show"
  resources :patients

  root 'patients#index'

end

app/models/pnote.rb
class Pnote < ActiveRecord::Base
	belongs_to :patient
end

app/controllers/pnotes_controller.rb
class PnotesController < ApplicationController
  before_action :set_pnote, only: [:show, :edit, :update, :destroy]

  # GET /pnotes
  # GET /pnotes.json
  def index
    @pnotes = Pnote.all
  end

  # GET /pnotes/1
  # GET /pnotes/1.json
  def show
  end

  # GET /pnotes/new
  def new
    @pnote = Pnote.new
  end

  # GET /pnotes/1/edit
  def edit
  end

  # POST /pnotes
  # POST /pnotes.json
  def create
    @pnote = Pnote.new(pnote_params)

    respond_to do |format|
      if @pnote.save
        format.html { redirect_to @pnote, notice: 'Pnote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pnote }
      else
        format.html { render action: 'new' }
        format.json { render json: @pnote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pnotes/1
  # PATCH/PUT /pnotes/1.json
  def update
    respond_to do |format|
      if @pnote.update(pnote_params)
        format.html { redirect_to @pnote, notice: 'Pnote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pnote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pnotes/1
  # DELETE /pnotes/1.json
  def destroy
    @pnote.destroy
    respond_to do |format|
      format.html { redirect_to pnotes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pnote
      @pnote = Pnote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pnote_params
      params.require(:pnote).permit(:para1, :para2, :para3, :patient_id)
    end
end

app/helpers/pnotes_helper.rb
module PnotesHelper
end

app/views/pnotes/_form.html.erb
<%= form_for(@pnote) do |f| %>
  <% if @pnote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pnote.errors.count, "error") %> prohibited this pnote from being saved:</h2>

      <ul>
      <% @pnote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :para1 %><br>
    <%= f.text_area :para1 %>
  </div>
  <div class="field">
    <%= f.label :para2 %><br>
    <%= f.text_area :para2 %>
  </div>
  <div class="field">
    <%= f.label :para3 %><br>
    <%= f.text_area :para3 %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.number_field :patient_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<br>
<br>
<!-- Main Accordian within a Fieldset -->

  <fieldset id="fieldsetNote1">
    <div id="heading1"></div>
    <ul id="noteList">
      <li>ITEMVALUE1</li>
          <li>  
                   
              <div class="FloatLt"> 
                  <textarea id="taItemValue1" name="taItemValue1"></textarea>
              </div>
              
              <div class="FloatLt">
                     <input type="button" id ="bItemValueToggle1" value="Toggle">
                     <input type="button" id ="bItemValue1Reset" value="Reset">
                     <input type="button" id ="bItemValue1Hist" value="Hist">
                     <br /><br />
                     <input type="button" id ="bItemValue1Dx" value="Dx:From'update'"> 
                     <br /> 
                     <input type="button" id ="bItemValue1DxYrNote" value="Dx:FromPsychYrNote"> 
                     <br /> 
                     <input type="button" id ="bItemValue1DxMsList" value="Dx:FromMedSpecList">
                     <br /> 
                     <input type="button" id ="bItemValue1Meds" value="Current Meds">
                     <div id="picture"></div>
                     <input type="text" id="dateDOA">
              </div>           
              <div class="clearLtONLY"></div><!---?Needed to stop jitter, or floats behaving badly with toggling-->
          </li>
       <li>Level2</li>
          <li>  
                   
              <div class="FloatLt"> 
                  <textarea id="taItemValue2" name="taItemValue2"></textarea>
              </div>
              
              <div class="FloatLt">
                     <input type="button" id ="bItemValueToggle2" value="Toggle">
                     <input type="button" id ="bItemValue2Reset" value="Reset">
                     <input type="button" id ="bItemValue2Hist" value="Hist">
                     <br /><br />
                     <input type="button" id ="bItemValue2Dx" value="Dx:From'update'"> 
                     <br /> 
                     <input type="button" id ="bItemValue2DxYrNote" value="Dx:FromPsychYrNote"> 
                     <br /> 
                     <input type="button" id ="bItemValue2DxMsList" value="Dx:FromMedSpecList">
                     <br /> 
                     <input type="button" id ="bItemValue2Meds" value="Current Meds">
                     <div id="picture"></div>
                     <input type="text" id="dateDOA">
              </div>           
              <div class="clearLtONLY"></div><!---?Needed to stop jitter, or floats behaving badly with toggling-->
          </li>   

      <li>Master </li>
            <li>
              <div class="FloatLt"> First Div</div>
              <div class="FloatLt"> Second Div</div>
              <div class="LtClear_g"></div>
              <div class="wrap1">Wrap1</div>
              <div class="wrap1">Wrap2</div>
              <div class="wrap1"><b>Professional Registration</b></div>
        <!-- <div class="clearLtONLY"></div> MAY NEED TO STOP JITTER etc -->
            </li>

        </ul>

        <!---SAVE BUTTONS-->           
      <!---Use as a visible line to delimit buttons-->
       <div class="bottomLine"></div>
       <!---GROOVE BOX FOR "ABOVE SAVE" STUFF i.e., ms dropdowns-->
            <!---<div class="groove">In the groove <input type="text" name="dateOrderDate2" id="dateOrderDate2" /></div>-->
      <div class="FloatLt">
          <!-- <div id="loading" class="loadingDiv3">Loading...</div> -->
          <div class="FloatLt"><input  type="button" id="bSaveTemp" value="TemporarySave"/></div>
          <div class="FloatLt"><input  type="button" id="bSavePerm" value="PermanentSave"/></div>
          <div class="FloatLt"><select name="selectHistory"  id="selectHistory"></select></div>
          <!---<div class="FloatLt"><select name="selectHistory2"  id="selectHistory2"></select></div>-->
          <div class="FloatLt"><input  type="text" name="tempSave" id="tempSave"></div>
          <div class="FloatLt"><input  type="text" name="permSave" id="permSave"></div>
          
      </div>
  </fieldset>

app/views/pnotes/edit.html.erb
<h1>Editing pnote</h1>

<%= render 'form' %>

<%= link_to 'Show', @pnote %> |
<%= link_to 'Back', pnotes_path %>

app/views/pnotes/index.html.erb
<h1>Listing pnotes</h1>

<table>
  <thead>
    <tr>
      <th>Para1</th>
      <th>Para2</th>
      <th>Para3</th>
      <th>Patient</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pnotes.each do |pnote| %>
      <tr>
        <td><%= pnote.para1 %></td>
        <td><%= pnote.para2 %></td>
        <td><%= pnote.para3 %></td>
        <td><%= pnote.patient_id %></td>
        <td><%= link_to 'Show', pnote %></td>
        <td><%= link_to 'Edit', edit_pnote_path(pnote) %></td>
        <td><%= link_to 'Destroy', pnote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pnote', new_pnote_path %>
<%#= link_to 'New Pnote', new_pnote_path, method: :post %>

<div id="placeholder"></div>

app/views/pnotes/new.html.erb
<h1>New pnote</h1>

<%= render 'form' %>

<%= link_to 'Back', pnotes_path %>

app/views/pnotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Para1:</strong>
  <%= @pnote.para1 %>
</p>

<p>
  <strong>Para2:</strong>
  <%= @pnote.para2 %>
</p>

<p>
  <strong>Para3:</strong>
  <%= @pnote.para3 %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @pnote.patient_id %>
</p>

<%= link_to 'Edit', edit_pnote_path(@pnote) %> |
<%= link_to 'Back', pnotes_path %>