config/routes.rb
AccordianNotes::Application.routes.draw do
  resources :users

  resources :apatients

  resources :pnotes

  get "smartmenus/show"
  get "menumaster/show"
  get "multiplemaster/show"
  resources :patients

  root 'patients#index'

end

app/models/apatient.rb
class Apatient < ActiveRecord::Base
end

app/controllers/apatients_controller.rb
class ApatientsController < ApplicationController
  before_action :set_apatient, only: [:show, :edit, :update, :destroy]

  # GET /apatients
  # GET /apatients.json
  def index
    @apatients = Apatient.all
    @apatient = Apatient.new
  end

  # GET /apatients/1
  # GET /apatients/1.json
  def show
  end

  # GET /apatients/new
  def new
    @apatient = Apatient.new
  end

  # GET /apatients/1/edit
  def edit
  end

  # POST /apatients
  # POST /apatients.json
  def create
    @apatient = Apatient.new(apatient_params)

    respond_to do |format|
      if @apatient.save
        format.html { redirect_to @apatient, notice: 'Apatient was successfully created.' }
        format.js {}
        format.json { render action: 'show', status: :created, location: @apatient }
      else
        format.html { render action: 'new' }
        format.json { render json: @apatient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apatients/1
  # PATCH/PUT /apatients/1.json
  def update
    respond_to do |format|
      if @apatient.update(apatient_params)
        format.html { redirect_to @apatient, notice: 'Apatient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @apatient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apatients/1
  # DELETE /apatients/1.json
  def destroy
    @apatient.destroy
    respond_to do |format|
      format.html { redirect_to apatients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apatient
      @apatient = Apatient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apatient_params
      params.require(:apatient).permit(:first_name, :last_name, :c_number, :date_of_admission)
    end
end

app/helpers/apatients_helper.rb
module ApatientsHelper
end

app/views/apatients/_form.html.erb
<%= form_for(@apatient, remote: true) do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br>
  <%= f.submit %>
<% end %>

app/views/apatients/create.js.erb
// $('body').html("This should overrite") 
//$('body').html("<%= escape_javascript(@pnote.para3) %>")
// $('#test1').html("<%= escape_javascript(@pnote.para3) %>")

 // $('#test1').html("<%= escape_javascript(render('showPartial')) %>")

 //$('#test1').html("<%= escape_javascript(@pnote.para3) %>")
 //$('#taItemValue1').html("<%= escape_javascript(@pnote.para3) %>")

 // $('#divContainer1').show();
 // $('#divContainer1').html('something');

 //$("<%= escape_javascript(render @apatient) %>").appendTo("#patients")
 $("<%= escape_javascript(render @apatient)%>").appendTo("#patients")

app/views/apatients/edit.html.erb
<h1>Editing apatient</h1>

<%= render 'form' %>

<%= link_to 'Show', @apatient %> |
<%= link_to 'Back', apatients_path %>

app/views/apatients/index.html.erb
<h1>Listing apatients</h1>


<ul id="patients">
  <% @apatients.each do |apatient| %>
    <li><%= apatient.first_name %> <%= apatient.last_name %></li>
  <% end %>
</ul>
<br>
<%= render 'form' %>

app/views/apatients/new.html.erb
<h1>New apatient</h1>

<%= render 'form' %>

<%= link_to 'Back', apatients_path %>

app/views/apatients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @apatient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @apatient.last_name %>
</p>

<p>
  <strong>C number:</strong>
  <%= @apatient.c_number %>
</p>

<p>
  <strong>Date of admission:</strong>
  <%= @apatient.date_of_admission %>
</p>

<%= link_to 'Edit', edit_apatient_path(@apatient) %> |
<%= link_to 'Back', apatients_path %>