config/routes.rb
AccordianNotes::Application.routes.draw do
  resources :users

  resources :apatients

  resources :pnotes

  get "smartmenus/show"
  get "menumaster/show"
  get "multiplemaster/show"
  resources :patients

  root 'patients#index'

end

app/views/layouts/_smartmenus.html.erb
<ul id="main-menu" class="sm sm-blue">
  <!-- <li><img src="/images/rails.jpg" width="57" height="30"></li> -->
  <li><%= image_tag 'rails.jpg', size: '35x43' %></li>
  <li><%= image_tag 'eCare3.gif', size: '35x25' %></li>
  <li><a href="#">Lists/Grids</a>
    <ul>
      <li><a href="<%= patients_path %>">Default Scaffold List</a></li>
      <li><a href="<%= apatients_path %>">Def Scaffold List + AJAX</a></li>
    </ul>
  </li>
  <li><a href="">Notes</a>
    <ul>
      <li><a href="<%= multiplemaster_show_path %>">ComplexMaster</a></li>
      <li><a href="#">SimpleMaster</a></li>
      <li><a href="">ShapeMeds-function</a></li>
      <li><a href="<%= pnotes_path %>">Default Scaffold Pnotes</a></li>
    </ul>
  </li>
  <li><a href="#">Menus</a>
    <ul>
      <li><a href="<%= menumaster_show_path %>">jQuery Menu Widget</a></li>
      <li><a href="<%= smartmenus_show_path %>">SmartMenus</a></li>
    </ul>
  </li>
  <li><a href="#">Item 3</a>
    <ul>
      <li><a href="#">Item 3-1</a>
      	<ul>
      		<li><a href="#">Item 3-1-1</a></li>
      		<li><a href="#">Item 3-1-2</a></li>
      		<li><a href="#">Item 3-1-3</a></li>
      		<li><a href="#">Item 3-1-4</a></li>
      	</ul>
      </li>
      <li><a href="#">Item 3-2</a></li>
      <li><a href="#">Item 3-3</a></li>
    </ul>
  </li>
  <li><a href="#">Item 3</a></li>
  
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AccordianNotes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/smartmenus.html.erb' %>

	<%= yield %>

</body>
</html>